version: 2

builds:
  - id: agevault
    main: ./cmd/agevault
    binary: agevault
    env:
      - CGO_ENABLED=0
    flags:
      - -trimpath
    ldflags:
      - -s -w -X main.version={{.Version}}
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64

archives:
  - formats:
      - tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        formats:
          - zip
    files:
      - LICENSE
      - README.md

checksum:
  name_template: checksums.txt
  algorithm: sha256

changelog:
  use: github
  sort: asc
  format: "{{ .SHA }}: {{ .Message }}"
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore:'
      - Merge pull request
      - Merge branch
  groups:
    - title: "New Features"
      regexp: '^.*?feat(\(.+\))??!?:.+$'
      order: 100
    - title: "Bug Fixes"
      regexp: '^.*?fix(\(.+\))??!?:.+$'
      order: 200
    - title: Other
      order: 9999

kos:
  - id: agevault
    repository: ghcr.io/zachcheung/agevault
    ldflags:
      - -s -w -X main.version={{.Version}}
    labels:
      org.opencontainers.image.source: "https://github.com/zachcheung/agevault-go"
      org.opencontainers.image.description: "age-encrypted secrets manager"
      org.opencontainers.image.licenses: MIT
      org.opencontainers.image.version: "{{.Version}}"
      org.opencontainers.image.revision: "{{.Commit}}"
      org.opencontainers.image.created: "{{.Date}}"
    tags:
      - "{{ .Version }}"
      - "{{ .Major }}.{{ .Minor }}"
      - "{{ if .Major }}{{ .Major }}{{ end }}"
      - latest
    platforms:
      - linux/amd64
      - linux/arm64
    bare: true

release:
  footer: |
    **Full Changelog**: https://github.com/zachcheung/agevault-go/compare/{{ .PreviousTag }}...{{ .Tag }}
