FROM golang:trixie AS build
WORKDIR /src
COPY . .
RUN CGO_ENABLED=0 go build -ldflags="-s -w" -trimpath -o /agevault ./cmd/agevault

FROM alpine
COPY --from=build /agevault /usr/local/bin/agevault
ENTRYPOINT ["agevault"]
